import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],

  products: [
    {
      name: 'Cart MSI',
      slug: 'cart msi',
      category: 'Shirts',
      image: '/images/cart-MSI.png',
      price: '70',
      brand: 'MSI',
      rating: 4.5,
      numReviews: 8,
      countInStock: 10,
      description:
        "A popular shirt from Nike. It is a great shirt for the summer Le commerce est l'une des plus anciennes et plus importantes inventions de l'humanité. Dans un contexte de mondialisation caractérisé par l'accélération des échanges commerciaux et financiers à l'échelle mondiale grâce au développement des technologies de l'information et de la communication, le e-commerce occupe une place croissante sur le marché de la vente..",
    },

    {
      name: 'MacBook Pro M2',
      slug: 'macbook pro m2',
      category: 'PC',
      image: '/images/macAir-m2.webp',
      price: '20200',
      brand: 'Mac',
      rating: 4.4,
      numReviews: 8,
      countInStock: 7,
      description: 'A popular shirt from Jason.',
    },
    {
      name: 'Ipad Pro 2022',
      slug: 'ipad pro',
      category: 'Tablette',
      image: '/images/ipadPro.webp',
      price: '1990',
      brand: 'Ipad',
      rating: 4.4,
      numReviews: 8,
      countInStock: 7,
      description: 'A popular shirt from Jason.',
    },
    {
      name: 'Appel watch',
      slug: 'apple watch',
      category: 'Montre',
      image: '/images/appleWatch.webp',
      price: '459.92',
      brand: 'Appel',
      rating: 4.4,
      numReviews: 8,
      countInStock: 7,
      description: 'A popular shirt from Jason.',
    },
    {
      name: 'Appel watch',
      slug: 'apple watch 2',
      category: 'Montre',
      image: '/images/appleWatch2.webp',
      price: '459.92',
      brand: 'Appel',
      rating: 4.4,
      numReviews: 8,
      countInStock: 7,
      description: 'A popular shirt from Jason.',
    },
    {
      name: 'Iphone 13 pro',
      slug: 'iphone 13 pro',
      category: 'Telephone',
      image: '/images/iphone13pro.webp',
      price: '1890',
      brand: 'Appel',
      rating: 4.4,
      numReviews: 8,
      countInStock: 7,
      description: 'A popular shirt from Jason.',
    },

    {
      name: 'RTX3080ti',
      slug: 'rxt3080ti',
      category: 'Shoes',
      image: '/images/rtx3080ti.png',
      price: '230',
      brand: 'Nike',
      rating: 4.8,
      numReviews: 8,
      countInStock: 35,
      description: 'A popular shoes from Nike.',
    },
    {
      name: 'Iphone 11 pro',
      slug: 'iphone 11 pro',
      category: 'Telephone',
      image: '/images/iphone11.webp',
      price: '1890',
      brand: 'Iphone',
      rating: 4.4,
      numReviews: 8,
      countInStock: 7,
      description: 'A popular shirt from Jason.',
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/images/look5.png',
      price: '70',
      brand: 'Johnson&Johnson',
      rating: 4.5,
      numReviews: 8,
      countInStock: 290,
      description:
        "A popular shirt from Nike. It is a great shirt for the summer Le commerce est l'une des plus anciennes et plus importantes inventions de l'humanité. Dans un contexte de mondialisation caractérisé par l'accélération des échanges commerciaux et financiers à l'échelle mondiale grâce au développement des technologies de l'information et de la communication, le e-commerce occupe une place croissante sur le marché de la vente..",
    },

    {
      name: 'Iphone 13 mini',
      slug: 'iphone 13 mini',
      category: 'Telephone',
      image: '/images/iphone13mini.webp',
      price: '1999',
      brand: 'Iphone',
      rating: 4.4,
      numReviews: 8,
      countInStock: 7,
      description: 'A popular shirt from Jason.',
    },
    {
      name: 'Hummer Shirt',
      slug: 'hummer-shirt',
      category: 'Shirts',
      image: '/images/look.png',
      price: '30',
      brand: 'Hummer',
      rating: 4.5,
      numReviews: 8,
      countInStock: 23,
      description:
        'A popular shirt from Hummer. It is a great shirt for the summer.',
    },

    {
      name: 'Zara Pants',
      slug: 'zara-pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: '95',
      brand: 'Zara',
      rating: 4.6,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular pants from Zara.',
    },

    {
      name: 'Jeans Pants',
      slug: 'jeans-pants',
      category: 'Pants',
      image: '/images/shirt3.jpg',
      price: '46',
      brand: 'Olivier',
      rating: 4,
      numReviews: 9,
      countInStock: 45,
      description: 'A popular pants from Jeans.',
    },
    {
      name: 'H&M Shirt',
      slug: 'H&M-shirt',
      category: 'Shirts',
      image: '/images/look1.png',
      price: '90',
      brand: 'H&M',
      rating: 4.5,
      numReviews: 8,
      countInStock: 52,
      description: 'A popular shirt from H&M.',
    },

    {
      name: 'Air Maxs',
      slug: 'air-maxsss',
      category: 'Shoes',
      image: '/images/nft6-removebg-preview.png',
      price: '170',
      brand: 'Nike',
      rating: 4.0,
      numReviews: 7,
      countInStock: 49,
      description: 'A popular shoes from Nike.',
    },

    {
      name: 'Golf Pantss',
      slug: 'golf-pantssss',
      category: 'Pants',
      image: '/images/nft5-removebg-preview.png',
      price: '70',
      brand: 'Johnson&Johnson',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description:
        'A popular shirt from Nike. It is a great shirt for the summer.',
    },

    {
      name: 'Addidas Shirt',
      slug: 'addidas-shirt',
      category: 'Shoes',
      image: '/images/shirt1.jpg',
      price: '65',
      brand: 'Addidas',
      rating: 4.5,
      numReviews: 9,
      countInStock: 35,
      description: 'A popular shirt from Addidas.',
    },
    {
      name: 'Addidas Shirtss',
      slug: 'addidas-shirtsss',
      category: 'Shoes',
      image: '/images/nft3-removebg-preview.png',
      price: '85',
      brand: 'Addidas',
      rating: 4.5,
      numReviews: 9,
      countInStock: 30,
      description: 'A popular shirt from Addidas.',
    },
  ],
};

export default data;
