const data = {
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      catgory: 'Shirts',
      image: '/images/pants1.jpg',
      price: '70',
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description:
        'A popular shirt from Nike. It is a great shirt for the summer.',
    },

    {
      name: 'PAris Shirt',
      slug: 'paris-shirt',
      catgory: 'Shirts',
      image: '/images/pants2.jpg',
      price: '70',
      brand: 'Jason',
      rating: 4.4,
      numReviews: 8,
      countInStock: 97,
      description: 'A popular shirt from Jason.',
    },

    {
      name: 'Airdax Shoes',
      slug: 'airdax-shoes',
      catgory: 'Shoes',
      image: '/images/pants3.jpg',
      price: '230',
      brand: 'Nike',
      rating: 4.8,
      numReviews: 8,
      countInStock: 35,
      description: 'A popular shoes from Nike.',
    },

    {
      name: 'Hummer Shirt',
      slug: 'hummer-shirt',
      catgory: 'Shirts',
      image: '/images/shirt1.jpg',
      price: '70',
      brand: 'Hummer',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description:
        'A popular shirt from Hummer. It is a great shirt for the summer.',
    },

    {
      name: 'Zara Pants',
      slug: 'zara-pants',
      catgory: 'Pants',
      image: '/images/pants2.jpg',
      price: '95',
      brand: 'Zara',
      rating: 4.6,
      numReviews: 8,
      countInStock: 80,
      description: 'A popular pants from Zara.',
    },

    {
      name: 'Jeans Pants',
      slug: 'jeans-pants',
      catgory: 'Pants',
      image: '/images/shirt3.jpg',
      price: '46',
      brand: 'Olivier',
      rating: 4,
      numReviews: 9,
      countInStock: 35,
      description: 'A popular pants from Jeans.',
    },
    {
      name: 'H&M Shirt',
      slug: 'H&M-shirt',
      catgory: 'Shirts',
      image: '/images/pants3.jpg',
      price: '90',
      brand: 'H&M',
      rating: 4.5,
      numReviews: 8,
      countInStock: 50,
      description: 'A popular shirt from H&M.',
    },

    {
      name: 'Air Max',
      slug: 'air-max',
      catgory: 'Shoes',
      image: '/images/shirt3.jpg',
      price: '170',
      brand: 'Nike',
      rating: 4.0,
      numReviews: 7,
      countInStock: 40,
      description: 'A popular shoes from Nike.',
    },

    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      catgory: 'Pants',
      image: '/images/shirt2.jpg',
      price: '70',
      brand: 'Johnson&Johnson',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description:
        'A popular shirt from Nike. It is a great shirt for the summer.',
    },

    {
      name: 'Addidas Shirt',
      slug: 'addidas-shirt',
      catgory: 'Shoes',
      image: '/images/shirt1.jpg',
      price: '65',
      brand: 'Addidas',
      rating: 4.5,
      numReviews: 9,
      countInStock: 35,
      description: 'A popular shirt from Addidas.',
    },
  ],
};

export default data;
